- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 25h
  - !type:RoleTimeRequirement
    role: JobCaptain
    time: 10h
  - !type:RoleTimeRequirement
    role: JobIAA
    time: 20h
  startingGear: ProsecutorGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ProsecutorGear
  equipment:
    id: ProsecutorPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetJuridical
  storage:
    back:
    - RubberStamProsecutor

- type: chameleonOutfit
  id: ProsecutorChameleonOutfit
  job: JobProsecutor
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
