- type: job
  id: STProsecutor
  name: stories-job-name-prosecutor
  description: stories-job-description-prosecutor
  playTimeTracker: STJobProsecutor
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 25h
  - !type:RoleTimeRequirement
    role: JobCaptain
    time: 10h
  - !type:RoleTimeRequirement
    role: JobIAA
    time: 20h
  startingGear: STProsecutorGear
  icon: "STJobIconProsecutor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: STProsecutorGear
  equipment:
    id: STProsecutorPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: STClothingHeadsetJuridical
  storage:
    back:
    - STRubberStamProsecutor

- type: chameleonOutfit
  id: STProsecutorChameleonOutfit
  job: STProsecutor
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
