- type: job
  id: STBrigmedic
  name: job-name-STBrigmedic
  description: job-description-STBrigmedic
  playTimeTracker: STJobBrigmedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 #10 часов
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 7200 #2 часа
  startingGear: STBrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Medical
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 200
  maxBankBalance: 250

- type: startingGear
  id: STBrigmedicGear
  equipment:
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    eyes: ClothingEyesHudMedSec
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatAMG

- type: chameleonOutfit
  id: STBrigmedicChameleonOutfit
  job: STBrigmedic
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretBrigmedic
    mask: ClothingMaskBreathMedicalSecurity