- type: entity #Раскидать в папки оригинала прототипа
  id: StunbatonBorg
  parent: Stunbaton
  name: дубинка
  description: Простая дубинка боргов.
  components:
  - type: PredictedBatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 100
